baseURL = "https://souren.github.io/souren-profile/"
languageCode = "en-us"
title = "Souren's Journal"
theme = "hugo-theme-stack"

[pagination]
  pagerSize = 2
  path = "page"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowToc = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true

  mainSections = ["root"]


  [params.author]
    name = "Souren Ghosh"
    email = "souren@example.com"
    avatar = "images/profile/souren.png"
    resize = "128x128"

  [params.sidebar]
    compact = false
    emoji = "ğŸ“"
    subtitle = "Engineer | Maker | Writer"

  [params.sidebar.avatar]
    enabled = true
    src = "https://ik.imagekit.io/7g2tgjtpt/souren-reduced.png?updatedAt=1760355002999"
    local = false

  [params.homeInfoParams]
    Title = "ğŸ‘‹ Welcome to Souren's Obsidian Journal"
    Content = "A collection of my thoughts, experiments, and notes â€” built with Hugo and Obsidian."


  [params.widgets]
    homepage = [
      { type = "search" },
      { type = "archives", params = { limit = 5 } },
      { type = "categories", params = { limit = 10 } },
    ]
  [params.footer]
    since = 2025
    poweredby = false
    custom = true
    text = "Â© 2025 Souren Ghosh â€” Built with â¤ï¸ using Hugo + Stack"

  [params.defaultImage.opengraph]
    enabled = false
    local = false
    src = ""

  [params.colorScheme]
    toggle = true
    default = "auto"

  [params.imageProcessing.cover]
    enabled = true

  [params.imageProcessing.content]
    enabled = true
  [params.article]
    math = false
    readingTime = true

  [params.article.license]
    enabled = true
    default = "Licensed under CC BY-NC-SA 4.0"

[menu]
  [[menu.social]]
    indentifier = "Github"
    url = "https://github.com/CaiJimmy/hugo-theme-stack"
    [menu.social.params]
        icon = "brand-github"

  # Home
  #[[menu.main]]
  #  identifier = "home"
  #  name = "ğŸ  Home"
  #  url = "/home/"
  #  weight = 1

  # About
  [[menu.main]]
    identifier = "about"
    name = "ğŸ‘¤ About"
    url = "/about/"
    weight = 2

  # Blog
  [[menu.main]]
    identifier = "blog"
    name = "ğŸ“ Blog"
    url = "/blog/"
    weight = 3

  # Projects
  [[menu.main]]
    identifier = "projects"
    name = "ğŸ›  Projects"
    url = "/projects/"
    weight = 4

  # Labs with dropdown
  [[menu.main]]
    identifier = "labs"
    name = "ğŸ”¬ Labs"
    url = "/labs/"
    weight = 5

  # Notes
  [[menu.main]]
    identifier = "notes"
    name = "ğŸ“’ Notes"
    url = "/notes/"
    weight = 6

  # Contact
  [[menu.main]]
    identifier = "contact"
    name = "âœ‰ï¸ Contact"
    url = "/contact/"
    weight = 7
