baseURL = "https://souren.github.io/souren-profile/"
languageCode = "en-us"
title = "Souren's Journal"
theme = "hugo-theme-stack"

[pagination]
  pagerSize = 4
  path = "page"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowToc = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true

mainSections = ["root"]



[params.author]
  name = "Souren Ghosh"
  email = "souren@example.com"
  avatar = "images/profile/souren.png"
  resize = "128x128"

[params.sidebar]
  compact = false
  emoji = "ğŸ“"
  subtitle = "Engineer | Maker | Writer"

[params.sidebar.avatar]
  enabled = true
  src = "https://ik.imagekit.io/7g2tgjtpt/souren-reduced.png?updatedAt=1760355002999"
  local = false

[params.homeInfoParams]
  Title = "ğŸ‘‹ Welcome to Souren's Obsidian Journal"
  Content = "A collection of my thoughts, experiments, and notes â€” built with Hugo and Obsidian."


[params.widgets]
  homepage = [
    { type = "search" },
    { type = "archives", params = { limit = 5 } },
    { type = "categories", params = { limit = 10 } },
    { type = "tag-cloud", params = { limit = 10 } }
  ]

[menu]

  # Home
  [[menu.main]]
    identifier = "home"
    name = "ğŸ  Home"
    url = "/home/"
    weight = 1

  # About
  [[menu.main]]
    identifier = "about"
    name = "ğŸ‘¤ About"
    url = "/about/"
    weight = 2

  # Blog
  [[menu.main]]
    identifier = "blog"
    name = "ğŸ“ Blog"
    url = "/blog/"
    weight = 3

  # Projects
  [[menu.main]]
    identifier = "projects"
    name = "ğŸ›  Projects"
    url = "/projects/"
    weight = 4

  # Labs with dropdown
  [[menu.main]]
    identifier = "labs"
    name = "ğŸ”¬ Labs"
    url = "/labs/"
    weight = 5

  # Notes
  [[menu.main]]
    identifier = "notes"
    name = "ğŸ“’ Notes"
    url = "/notes/"
    weight = 6

  # Contact
  [[menu.main]]
    identifier = "contact"
    name = "âœ‰ï¸ Contact"
    url = "/contact/"
    weight = 7
